M48
; DRILL file {KiCad 9.0.7+1} date 2026-02-20T15:45:36+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-20T15:45:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X210.6Y-128.26
T2
X220.2Y-147.8
T1
G00X203.55Y-128.26
M15
G01X203.25Y-128.26
M16
G05
M30
